### ISSUE TITLE
chrome

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/wordCollector#2]
#### todo
- [ ] contentscript: check the length of the sentence which will be uploaded and make sure it's not too long
- [ ] how to refactor contentscript.coffee
  - [ ] avoid too much $('<something>') by reading html file
- [ ] write over with angular js
#### bugs
- the dropdown of the meanings in dictionary div sometimes doesn't work
  - especially, alc side and especially when invoked from web text not from floating input
- unless set the valid category, user can't upload data

**Comment by hi-ogawa** [comment]
#### finished
- [x] popup: see available categories from popup and set the destination of uploading there
- [x] popup: remove ext_div and make it possible to word search from popup
- [x] popover generation function
- [x] toggling (inserting) contentscript execution from popup
- [x] popover behaviour
  - [x] scrollable popover content
  - [x] hide when mouse leave
- [x] shootAntUpload is duplicated in youtube.

**Comment by hi-ogawa** [comment]
#### bugs
- the dropdown of the meanings in dictionary div sometimes doesn't work
 - especially, alc side and especially when invoked from web text not from floating input
